- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-southeast-1
      instance_type: t2.micro
      ami: ami-76144b0a  # Redhat
      keypair: ansible_demo # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "AKIAILG2NZIU6UKO2UPQ"
         aws_secret_key: "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"
         group: launch-wizard-1  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "harshDemo"
         instance_tags:
            Name: "Demo"
         vpc_subnet_id: "subnet-6e213b09"
         assign_public_ip: yes
      register: ec2

    - debug:
        msg: "{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"

    - name: wait for ssh port
      wait_for: port=22 host="{{ item['private_ip'] }}" timeout=120 state=started
      with_items: "{{ ec2.instances }}"

    - name: Create a new inventory
      add_host:
        host_name: "{{ item['private_ip'] }}"
        ansible_user: ec2-user
        ansible_ssh_key: /root/.ssh/my.pem
        groups: webserver
      with_items: "{{ ec2.instances }}"

    - set_fact: ip_list= "[]"
