---

- hosts: localhost

- tasks:
    - debug: msg="Append two lists or merge"
        - set_fact:
            list_one: 
              - 1
              - 2
              - 3

        - set_fact:
            list_two:
              - 4
              - 5
              - 6

        - set_fact: merged_list= "{{ list _one + list_two }}"

    - debug: var=merged_list
